# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Solarpunk
description: > # this means to ignore newlines until next variable
  Solarpunk literature and other resources
license: "made with love by Ian Dennis Miller"

# Links
baseurl: "/solarpunk" # the subpath of your site, e.g. /blog
url: "https://iandennismiller.github.io" # the base hostname & protocol for your site
permalink: none

# include/exclude files
include: ["_pages", "_root"]
exclude: ["docs", "Readme.md", "Todo.md", "Makefile", "vendor", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-sitemap
  - jekyll-datapage-generator

page_gen-dirs: false

page_gen:
  - data: 'aesthetic'
    name: 'id'
    template: 'gen-item'
    dir: 'aesthetic'
    index_files: false
  - data: 'practice'
    name: 'id'
    template: 'gen-item'
    dir: 'practice'
    index_files: false
  - data: 'theory'
    name: 'id'
    template: 'gen-item'
    dir: 'theory'
    index_files: false
  - data: 'city'
    name: 'id'
    template: 'gen-item'
    dir: 'city'
    index_files: false
